# Generated by Django 5.0.3 on 2024-04-22 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.IntegerField(max_length=11)),
                ('message', models.TextField(blank=True)),
                ('number_of_guests', models.IntegerField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=6)),
                ('image', models.ImageField(upload_to='food/')),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
