# Generated by Django 5.0.3 on 2024-04-22 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resturnat', '0003_quotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
