# Generated by Django 5.0.3 on 2024-04-22 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resturnat', '0004_book_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='number_of_guests',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='book',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
