# Generated by Django 5.0.4 on 2024-04-22 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resturnat', '0005_alter_book_number_of_guests_alter_book_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('message', models.TextField(blank=True)),
                ('number_of_guests', models.CharField(max_length=4)),
                ('date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
