# Generated by Django 5.0.4 on 2024-05-26 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resturnat', '0008_qoute_delete_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='food'),
        ),
    ]
